// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdvemexeuorsbcermvqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkdmVtZXhldW9yc2JjZXJtdnFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4Mjk3ODQsImV4cCI6MjA3NDQwNTc4NH0.MPlRgtLwczGoIo8K6_Sn0zpk2yjZqT-GsNI9IUSjRJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});